train_fixed:
  batch_size: 8
  epoch_num: 160
  # Logging
  # Logging
  earlystopping_target: val_meanIoU
  earlystopping_patience: 35
  plot:
    - loss
    - sem_loss
    - bd_loss
    - vcf_loss
    - vcf_meanIoU
    - vcf_f1Score
    - meanIoU
    - f1Score
  #-------------------------  
  #model_name: PIDNet
  #model_parameters:
  #
  #-------------------------
  metirc_func:
    - meanIoU
    - f1Score
  loss_name: ce
  model_name: pidnet_s
  #Unet3Plus
  restart_epoch: 30
model_fixed:
  in_channels: 3
  class_num: 12
  # unet은 무조건 True
  #use_transpose: False
  #-------------------------
  #model_name: Unet3Plus
  #model_parameters:
  #  in_channels: 3
  #  class_num: 12
  #  enc_use_drop: 9
  #  skip_use_drop: 9
  #  use_merge_drop: 9
  #  use_transpose: False
  #
  #-------------------------
initial_learning_rate:
  - 1.0e-3
  - 1.0e-4
  - 1.0e-5
minimum_learning_rate_relative_to_iterative:
  - 1.0e-3
  #- 0.0
p3: 0
p4: 0
p5: 0
# enc_use_drop: 4
#dec_use_drop: 0
# use_skip_drop: 4
# use_dec_drop: 4